### ISSUE TITLE
Teleports don't work

### ISSUE THREAD

**Issue by danzio** [DArkHekRoMaNT/TeleportationNetwork#13]
### Mod Version

1.10.1

### Game Version

1.18.0 (stable)

### OS

Windows

### Play mode

Singleplayer

### Problem

Looks like in stable version teleports are not working at all: I attached screenshot, as you can see, teleport block missing textures, neither animation nor dialog window (with tp points) appear.

### Screenshots

![изображение](https://user-images.githubusercontent.com/17835496/233545707-d3893458-9d59-4f00-bb9c-3b1aeaa19339.png)

**Comment by DArkHekRoMaNT** [comment]
Looks like a lost BlockEntity. Just replace the block in the creative. Did you run this world without the mod?

**Comment by danzio** [comment]
I ran this world previously in unstable version and all was pretty fine to me. Perhaps issue connected with version updating.


От: ***@***.***>
Отправлено: 21 апреля 2023 г. в 8:26
Кому: ***@***.***>
Копия: ***@***.***>; ***@***.***>
Тема: Re: [DArkHekRoMaNT/TeleportationNetwork] Teleports don't work (Issue #13)


Looks like a lost BlockEntity. Just replace the block in the creative. Did you run this world without the mod?
