### ISSUE TITLE
Teleporters stop generating after the newest mod update.

### ISSUE THREAD

**Issue by Khaligufzel** [DArkHekRoMaNT/TeleportationNetwork#15]
### Mod Version

1.11.0-rc.1

### Game Version

1.18.5

### OS

Windows

### Play mode

Multiplayer

### Problem

Teleporters are not generated anymore after the newest mod update.

Could it be because we changed the main spawn location? World coordinates changed because of that.

Even with these settings:

  "MinTeleportDistance": {
    "Description": "Minimal distance between teleport structures",
    "Limits": "System.Int32 value from 0 to 2147483647",
    "Default": 4096,
    "Value": 1024
  }

"TeleportGridSize": {
    "Description": "Distance between teleports",
    "Limits": "System.Int32 value from 32 to 2147483647",
    "Default": 4096,
    "Value": 1024
  }

  "TeleportGridAreaRadius": {
    "Description": "Teleport position random spread relative to the grid",
    "Limits": "System.Int32 value from 1 to 2147483647",
    "Default": 512,
    "Value": 512
  }

### Logs

```bash
No errors.
```

### Mods

```bash
A Culinary Artillery @ 1.0.12 | Universal
  Advanced Smithing @ 1.3.0 | Universal
  Bannerdoria Signs @ 1.0.1 | Universal
  Better Crates @ 1.6.0 | Universal
  BetterRuins @ 0.1.1 | Universal
  chiseltools @ 1.8.4 | Universal
  Faster Ladder Climbing @ 1.0.0 | Universal
  More Nails @ 1.0.1 | Universal
  The Nameless Lands @ 1.2.0 | Universal
  Pie On The Shelf @ 1.0.0 | Universal
  Primitive Survival @ 3.1.9 | Universal
  Ranged Weapons @ 0.6.2 | Universal
  SpeedBoostCraftables @ 1.0.2 | Universal
  Essentials @ 1.18.5 | Universal
  Wildcraft @ 1.6.6 | Universal
  Alchemy @ 1.6.11 | Universal
  Beehive Kiln @ 1.2.1 | Universal
  Better Firepit @ 1.1.0 | Universal
  Reignited @ 1.1.0 | Universal
  Carry On @ 1.1.0 | Universal
  CommonLib @ 2.0.5 | Universal
  Expanded Foods @ 1.6.6 | Universal
  From Golden Combs @ 1.4.16-rc.2 | Universal
  HUD Clock - Server extension @ 1.3.1 | Server
  Medieval Expansion @ 3.9.1 | Universal
  Pet AI @ 1.7.4 | Universal
  Place Every Item @ 1.4.0 | Server
  Simple Pottery Wheel @ 1.0.1 | Universal
  Simple Footsteps @ 1.0.4 | Universal
  Stone Bake Oven @ 1.0.1 | Universal
  Creative Mode @ 1.18.5 | Universal
  Survival Mode @ 1.18.5 | Universal
  Wild Farming Revival @ 1.0.5 | Universal
  Workbench Expansion @ 1.6.2 | Universal
  XLib @ 0.7.1 | Universal
  One Bed Sleeping @ 2.2.0 | Universal
  Expanded Matter @ 2.1.1 | Universal
  Stone Quarry @ 3.0.0 | Universal
  Teleportation Network @ 1.11.0-rc.1 | Universal
  Th3Essentials @ 2.3.0 | Server
  Bigger Windmill @ 0.2.0 | Universal
  Wolf taming @ 1.7.3 | Universal
  XSkills @ 0.7.1 | Universal
  Bricklayers @ 2.0.0 | Universal
  Wildcraft patch for XSkills @ 0.2.0 | Universal
```

**Comment by Khaligufzel** [comment]
A little update:
I think they DO generate, but they are very RARE.

**Comment by DArkHekRoMaNT** [comment]
Keep in mind that teleports are now independent of chunk generation order. In old versions, moving in a straight line, you would probably always find a teleport. Now you can move between grid nodes, which may make it seem that teleports are almost not generated.

Try to move from any exists new teleport in a straight line, if in your case the view distance is 512 or higher, then you should quickly find a new teleport. You can also decrease the AreaRadius to make the teleport line more clear.

![image](https://github.com/DArkHekRoMaNT/TeleportationNetwork/assets/15899143/7070e15d-ba2e-4ca6-8e50-c042ff3d1173)

P.S. MinTeleportDistance no longer affects generation (I will need to remove this)

**Comment by Khaligufzel** [comment]
Thanks for the answer!

I will test it a bit more in that case!

**Comment by digital-r** [comment]
Another update for teleport generation: in oceanic worlds teleports frequently generated deep underwater. There is no columns underneath anymore. Even in shallow water teleport can generated partially submerged

**Comment by DArkHekRoMaNT** [comment]
No longer relevant for 1.12+

**Comment by DArkHekRoMaNT** [comment]
> Another update for teleport generation: in oceanic worlds teleports frequently generated deep underwater. There is no columns underneath anymore. Even in shallow water teleport can generated partially submerged

This is fixed too
