### ISSUE TITLE
Problem with Teleportation Network

### ISSUE THREAD

**Issue by pkwild54** [DArkHekRoMaNT/TeleportationNetwork#2]
So, I'm playing on 1.15.5, heavily modded.  Just updated to the newest version of Teleportation Network, but every time I try to enable a teleporter, it causes issues.  When I break blocks, I get nothing and I can't right-click to pick up stones.

**Comment by DArkHekRoMaNT** [comment]
I do not modify in any way breaking blocks or picking up stones o.O
Are you sure this is related to TpNet? What other mods have you updated?

**Comment by pkwild54** [comment]
I have not updated any other mods. It happened when I fixed the broken
teleporter. However, I started the world with the old version and then
repaired the teleporter with the new version. I'm going to try a completely
new world to see if it does it again.

Sent from my Samsung Galaxy S9

Pamela K Wild

**Comment by DArkHekRoMaNT** [comment]
What version did you update from?

**Comment by pkwild54** [comment]
TeleportationNetwork_v1.15.5_v1.4.1.zip

[image: Cute Christmas Quotes And Sayings. QuotesGram]

**Comment by pkwild54** [comment]
Just tried it with a brand new world, and it did the same thing.  Here is
the list of mods I'm using.

[image: image.png]
[image: Cute Christmas Quotes And Sayings. QuotesGram]

**Comment by pkwild54** [comment]
OK.  Fixed the problem.  Here is my new list of mods.  Not sure which one
might have caused the problem, though.

[image: image.png]

[image: Cute Christmas Quotes And Sayings. QuotesGram]

**Comment by DArkHekRoMaNT** [comment]
No images on GitHub, only image name

**Comment by pkwild54** [comment]
The list was meant to be compared to the other one, so you would know which
ones I deleted.

[image: Cute Christmas Quotes And Sayings. QuotesGram]

**Comment by DArkHekRoMaNT** [comment]
I mean it looks like [image: image.png] for me

**Comment by pkwild54** [comment]
OK.  Here is a list of the mods I removed:

Alchemy
BamBOOM
Clay Kaboomables
Ferrospear
Meteoric Iron Expansion
Player Corpse
Resin Rennaisance
RicherThanDirt
Roofs
Rope Bridges
Rope Buckets
ST-Alpha Weapon Pack

[image: Cute Christmas Quotes And Sayings. QuotesGram]

**Comment by DArkHekRoMaNT** [comment]
Possibly unrelated to tpnet, open again if problem persists
