### ISSUE TITLE
None of the unlocked teleporters are accessible in survival mode

### ISSUE THREAD

**Issue by bluelightning32** [DArkHekRoMaNT/TeleportationNetwork#5]
I've unlocked a few teleporters, but none of them let me teleport between them, even the very close ones.
![image](https://user-images.githubusercontent.com/21202621/192225641-cc10cc93-0a01-4fe1-a39b-a6f98d734d46.png)

They work in creative mode.

```
[minecraft@sasami live_data]$ cat ModConfig/tpnet.json 
{
  "LegacySharedTeleports": {
    "Comment": "All activated teleport to all players",
    "Default": false,
    "Val": false
  },
  "Unbreakable": {
    "Comment": null,
    "Default": true,
    "Val": true
  },
  "StabilityTeleportMode": {
    "Comment": "Enabling the teleport stability mode. If on, teleport will be unstable at low temporal stability (lower than StabilityConsumable) and during storms. If always, then everytime will be unstable.[on, off, always]",
    "Default": "on",
    "Val": "on"
  },
  "StabilityConsumable": {
    "Comment": "Consumption of stability for teleport if stability is not enough <data deleted>. Percentage values from 0 to 1",
    "Default": 0.2,
    "Val": 0.2
  },
  "UnstableTeleportRange": {
    "Comment": "Range for unstable teleport <data deleted>",
    "Default": 500,
    "Val": 500
  },
  "SubNetworks": false,
  "MaxNetworkDistance": 10000,
  "SharedTeleports": false,
  "TeleportCooldown": 5000
```

**Comment by bluelightning32** [comment]
It turns out that setting `"SubNetworks": false` on the server is not sufficient. SubNetworks have to be turned off in the client.

The easiest way to find the file is on the startup screen (where one would typically click "Multiplayer"), click "Mod Manager", then click "Open Mods Folder". Go up one level to the VintagestoryData folder, then go in the ModConfig folder. Edit the tpnet.json file. Change this line:
```
  "SubNetworks": true,
```
to:
```
  "SubNetworks": false,
```

Save the file and restart Vintage Story.

**Comment by DArkHekRoMaNT** [comment]
There are no subnetworks in 1.8 yet, but in any case, the new config system is automatically synchronized from the server
