### ISSUE TITLE
Unable to paste tp structures in v. 1.7.1

### ISSUE THREAD

**Issue by Ovadex** [DArkHekRoMaNT/TeleportationNetwork#7]
When trying to paste a structure the following error happens.

27.9.2022 02:43:00 [Chat] Can't import /home/ovadex/.config/VintagestoryData/Cache/unpack/TeleportationNetwork_v1.17.3_v1.7.1.zip_ed6acefac007/assetsworldgen/schematics/tpnet/teleport/trader.json, it does not exist @ 0

It looks to be a simple typo.

**Comment by DArkHekRoMaNT** [comment]
Fixed in 1.7.2
