### ISSUE TITLE
black square instead green animations

### ISSUE THREAD

**Issue by dann1kid** [DArkHekRoMaNT/TeleportationNetwork#9]
### Mod Version

TeleportationNetwork_v1.17.9_v1.8.0-rc.1

### Game Version

1.17.9

### OS

Windows

### Play mode

Multiplayer

### Problem

black square instead green animations, no menus appeared

### Logs

7.1.2023 15:55:30 [Notification] Server logger started.
7.1.2023 15:55:30 [Notification] Game Version: v1.17.9 (Stable)
7.1.2023 15:55:30 [Notification] C# Framework: .net Framework 4.0.30319.42000
7.1.2023 15:55:30 [Event] Launching server...
7.1.2023 15:55:31 [Event] Server v1.17.9, network v1.17.8, api v1.7.0
7.1.2023 15:55:31 [Notification] Entering runphase Initialization
7.1.2023 15:55:31 [Event] Loading configuration...
7.1.2023 15:55:31 [Notification] Entering runphase Configuration
7.1.2023 15:55:32 [Notification] Loading savegame
7.1.2023 15:55:32 [Notification] Loaded existing save game data. Playstyle: surviveandbuild, Playstyle Lang code: surviveandbuild-bands, WorldType: surviveandbuild-bands
7.1.2023 15:55:32 [Notification] Savegame ./data\Saves\default.vcdbs loaded
7.1.2023 15:55:32 [Notification] World size = 102400 256 102400
7.1.2023 15:55:32 [Notification] Start discovering assets
7.1.2023 15:55:32 [Notification] Found 1 base assets in category blocktypes
7.1.2023 15:55:32 [Notification] Found 0 base assets in category itemtypes
7.1.2023 15:55:32 [Notification] Found 20 base assets in category lang
7.1.2023 15:55:32 [Notification] Found 0 base assets in category patches
7.1.2023 15:55:32 [Notification] Found 22 base assets in category config
7.1.2023 15:55:32 [Notification] Found 0 base assets in category worldproperties
7.1.2023 15:55:32 [Notification] Found 0 base assets in category sounds
7.1.2023 15:55:32 [Notification] Found 97 base assets in category shapes
7.1.2023 15:55:32 [Notification] Found 30 base assets in category textures
7.1.2023 15:55:32 [Notification] Found 0 base assets in category recipes
7.1.2023 15:55:32 [Notification] Found 0 base assets in category worldgen
7.1.2023 15:55:32 [Notification] Found 2 base assets in category entities
7.1.2023 15:55:32 [Notification] Found 172 base assets in total
7.1.2023 15:55:32 [Event] Building assets...
7.1.2023 15:55:32 [Notification] Entering runphase AssetsReady
7.1.2023 15:55:32 [Notification] Will search the following paths for mods:
7.1.2023 15:55:32 [Notification]     G:\gsm\servers\3\serverfiles\Mods
7.1.2023 15:55:32 [Notification]     G:\gsm\servers\3\serverfiles\data\Mods
7.1.2023 15:55:32 [Notification] Found 13 mods (0 disabled)
7.1.2023 15:55:32 [Error] [carryablelogwithresin] Could not resolve some dependencies:
7.1.2023 15:55:32 [Error] [carryablelogwithresin]     carrycapacity@0.0.0 - Missing
7.1.2023 15:55:32 [Error] [wolftaming] Could not resolve some dependencies:
7.1.2023 15:55:32 [Error] [wolftaming]     petai@1.5.4 - Missing
7.1.2023 15:55:32 [Notification] Mods, sorted by dependency: weaponpacka, betterdrifters, carryablelogwithresin, necessaries, game, medievalexpansion, tpnet, usefulstuff17, creative, survival, wolftaming, xrowboat, Th3Essentials
7.1.2023 15:55:33 [Notification] Instantiated 89 mod systems from 11 enabled mods
7.1.2023 15:55:33 [Notification] External Origins in load order: modorigin@G:\gsm\servers\3\serverfiles\assets\creative\, modorigin@G:\gsm\servers\3\serverfiles\assets\survival\, mod@AlphaWeaponPack_v1.3.1.zip, mod@BetterDrifters_v2.1.3_1.zip, mod@necessaries_v1.17.1-1.1.3.zip, mod@medievalexpansion-3.8.1.zip, mod@TeleportationNetwork_v1.17.9_v1.8.0-rc.1.zip, mod@usefulstuff17_v1.0.2.zip, mod@xrowboat_0.0.5.zip, mod@Th3Essentials_2.0.0.zip
7.1.2023 15:55:33 [Notification] Found 391 external assets in category blocktypes
7.1.2023 15:55:33 [Notification] Found 265 external assets in category itemtypes
7.1.2023 15:55:33 [Notification] Found 47 external assets in category lang
7.1.2023 15:55:33 [Notification] Found 35 external assets in category patches
7.1.2023 15:55:33 [Notification] Found 49 external assets in category config
7.1.2023 15:55:33 [Notification] Found 24 external assets in category worldproperties
7.1.2023 15:55:33 [Notification] Found 26 external assets in category sounds
7.1.2023 15:55:33 [Notification] Found 2900 external assets in category shapes
7.1.2023 15:55:33 [Notification] Found 170 external assets in category textures
7.1.2023 15:55:33 [Notification] Found 421 external assets in category recipes
7.1.2023 15:55:33 [Notification] Found 418 external assets in category worldgen
7.1.2023 15:55:33 [Notification] Found 62 external assets in category entities
7.1.2023 15:55:33 [Notification] Found 2 external assets in category compatibility
7.1.2023 15:55:33 [Notification] Reloaded lang file with mod assets
7.1.2023 15:55:33 [Event] Medieval Expansion Mod v3.8.1 loading
7.1.2023 15:55:35 [Notification] JsonPatch Loader: 237 патчей всего, успешно применено 221 патчей, отсутствующие файлы в 16 патчах, невыполненны условия в 74 патчах, нет проблем
7.1.2023 15:55:36 [Notification] Loaded 2656 unique items
7.1.2023 15:55:39 [Notification] Loaded 12254 unique blocks
7.1.2023 15:55:39 [Notification] Loaded 222 unique entities
7.1.2023 15:55:39 [Notification] BlockLoader: Entities, Blocks and Items loaded
7.1.2023 15:55:39 [Event] Remapping blocks and items...
7.1.2023 15:55:40 [Event] 6 cooking recipes loaded
7.1.2023 15:55:41 [Event] 707 crafting recipes loaded from 269 files
7.1.2023 15:55:41 [Event] 7 metal alloys loaded
7.1.2023 15:55:41 [Event] 319 smithing recipes loaded
7.1.2023 15:55:41 [Event] 71 clay forming recipes loaded
7.1.2023 15:55:41 [Event] 42 knapping recipes loaded
7.1.2023 15:55:41 [Event] 136 barrel recipes loaded
7.1.2023 15:55:41 [Notification] Entering runphase AssetsFinalize
7.1.2023 15:55:42 [Event] Server assets loaded, parsed, registered and finalized
7.1.2023 15:55:42 [Event] Initialising systems...
7.1.2023 15:55:42 [Notification] Entering runphase LoadGamePre
7.1.2023 15:55:42 [Notification] Reloaded 19 weather patterns, 5 wind patterns and 5 weather events
7.1.2023 15:55:42 [Notification] Started 81 systems on Server:
7.1.2023 15:55:42 [Notification]     Mod 'VSEssentials.dll' (game):
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.Core
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.EntityPartitioning
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ErrorReporter
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.ModCompatiblityUtil
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.NoObf.ModJsonPatchLoader
7.1.2023 15:55:42 [Notification]         Vintagestory.Essentials.PathfindSystem
7.1.2023 15:55:42 [Notification]         Vintagestory.Essentials.PathFindDebug
7.1.2023 15:55:42 [Notification]         Vintagestory.Essentials.PathfindingAsync
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.JsonExport
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.ModBasicBlocksLoader
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.LeafBlockDecay
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.POIRegistry
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.RoomRegistry
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.WeatherSystemCommands
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.WeatherSystemServer
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.WorldMapManager
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.LoadColorMaps
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ClothManager
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GridRecipeLoader
7.1.2023 15:55:42 [Notification]     Mod 'VSSurvivalMod.dll' (survival):
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenPatchesPrePass
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenSnowLayer
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenTerra
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.SaplingControl
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.SurvivalCoreSystem
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenTerraPostProcess
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.ChiselBlockBulkSetMaterial
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenFromHeightmap
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenRockStrataNew
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.NpcControl
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenCreatures
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenMaps
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.WgenCommands
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.DebugSystem
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.UpgradeTasks
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.MyceliumSystem
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ModSystemAuction
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.LiquidItemStackRenderer
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.CharacterSystem
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.FruitingSystem
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ModSystemRifts
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ModSystemRiftWeather
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ModTemperature
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.CustomSpawnConditions
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.SystemTemporalStability
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ModSystemWearableStats
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ModSystemBlockReinforcement
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.TemporalStabilityEffects
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ModJournal
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ModLootRandomizer
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.ModSleeping
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.TeleporterManager
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.Mechanics.MechanicalPowerMod
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenDeposits
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenStructures
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenCaves
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenBlockLayers
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenPonds
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenStructuresPosPass
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenVegetationAndPatches
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.RecipeRegistrySystem
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenRivulets
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenLightSurvival
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.RecipeLoader
7.1.2023 15:55:42 [Notification]         Vintagestory.GameContent.TraderOutfits
7.1.2023 15:55:42 [Notification]     Mod 'TeleportationNetwork_v1.17.9_v1.8.0-rc.1.zip' (tpnet):
7.1.2023 15:55:42 [Notification]         TeleportationNetwork.ConfigManager
7.1.2023 15:55:42 [Notification]         TeleportationNetwork.Core
7.1.2023 15:55:42 [Notification]         TeleportationNetwork.SaveManager
7.1.2023 15:55:42 [Notification]         TeleportationNetwork.TeleportManager
7.1.2023 15:55:42 [Notification]         TeleportationNetwork.GenTeleportStructures
7.1.2023 15:55:42 [Notification]     Mod 'VSCreativeMod.dll' (creative):
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.Core
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.WorldEdit.WorldEdit
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenBlockLayersFlat
7.1.2023 15:55:42 [Notification]         Vintagestory.ServerMods.GenLightCreative
7.1.2023 15:55:42 [Notification]     Mod 'AlphaWeaponPack_v1.3.1.zip' (weaponpacka):
7.1.2023 15:55:42 [Notification]         CustomWeaponSpeed.WeaponPackAlphaMod
7.1.2023 15:55:42 [Notification]     Mod 'necessaries_v1.17.1-1.1.3.zip' (necessaries):
7.1.2023 15:55:42 [Notification]         necessaries.src.Necessaries
7.1.2023 15:55:42 [Notification]     Mod 'medievalexpansion-3.8.1.zip' (medievalexpansion):
7.1.2023 15:55:42 [Notification]         gates.src.MedievalExpansionMod
7.1.2023 15:55:42 [Notification]     Mod 'usefulstuff17_v1.0.2.zip' (usefulstuff17):
7.1.2023 15:55:42 [Notification]         UsefulStuff.UsefulStuff
7.1.2023 15:55:42 [Notification]         UsefulStuff.GasHelper
7.1.2023 15:55:42 [Notification]     Mod 'xrowboat_0.0.5.zip' (xrowboat):
7.1.2023 15:55:42 [Notification]         XRowboat.XRowboatMod
7.1.2023 15:55:42 [Notification]     Mod 'Th3Essentials_2.0.0.zip' (Th3Essentials):
7.1.2023 15:55:42 [Notification]         Th3Essentials.Th3Essentials
7.1.2023 15:55:43 [Event] [tpnet] Start loading data
7.1.2023 15:55:43 [Event] [tpnet] Data loaded for 7 teleports
7.1.2023 15:55:43 [Event] [tpnet] Check teleport exists (async)
7.1.2023 15:55:44 [Notification] Server map set
7.1.2023 15:55:44 [Notification] Entering runphase GameReady
7.1.2023 15:55:44 [Event] Starting world generators...
7.1.2023 15:55:44 [Notification] Entering runphase WorldReady
7.1.2023 15:55:46 [Notification] Reloaded 35 tree generators
7.1.2023 15:55:46 [Event] Loading 7x7x8 spawn chunks...
7.1.2023 15:55:46 [Event] 0% (49 in queue)
7.1.2023 15:55:47 [Event] Begin game ticking...
7.1.2023 15:55:47 [Notification] Entering runphase RunGame
7.1.2023 15:55:47 [Notification] Successfully loaded 1077 waypoints
7.1.2023 15:55:47 [Notification] Server Advertising enabled. Attempt to register at the master server.
7.1.2023 15:55:47 [Notification] VerifyPlayerAuth is off. Will not register to master server
7.1.2023 15:55:47 [Notification] Registering to master server...
7.1.2023 15:55:47 [Notification] Starting server threads
7.1.2023 15:55:48 [Notification] Master server response status: ok
7.1.2023 15:55:48 [Event] Выделенный сервер now running on Port 42427 and ip 0.0.0.0!
7.1.2023 15:55:48 [Notification] All clients disconnected, pausing game calendar.
7.1.2023 15:55:49 [Warning] Server overloaded. A tick took 864ms to complete.
7.1.2023 15:55:53 [Notification] A Client attempts connecting via TCP, assigning client id 1
7.1.2023 15:55:53 [Notification] Client uid MDI0MDZjNDQ3MDdmNTNmNjgzY2U4NzViNTQ2ZDY5OWI= attempting identification. Name: Prikol
7.1.2023 15:55:53 [Notification] Sending server identification with remap False.  Server control privilege is False
7.1.2023 15:55:53 [Notification] Placing player at 73488,3828125 110 48422,03515625
7.1.2023 15:55:53 [Event] Client disconnected.
7.1.2023 15:55:53 [Notification] Last player disconnected, compacting large object heap...
7.1.2023 15:55:54 [Warning] Server overloaded. A tick took 953ms to complete.
7.1.2023 15:55:58 [Warning] Server overloaded. A tick took 623ms to complete.
7.1.2023 15:56:00 [Notification] A Client attempts connecting via TCP, assigning client id 2
7.1.2023 15:56:00 [Notification] Client uid MDI0MDZjNDQ3MDdmNTNmNjgzY2U4NzViNTQ2ZDY5OWI= attempting identification. Name: Prikol
7.1.2023 15:56:00 [Notification] Delayed join, need to load one spawn chunk first.
7.1.2023 15:56:00 [Notification] Sending server identification with remap False.  Server control privilege is False
7.1.2023 15:56:00 [Notification] Placing player at 73488,3828125 110 48422,03515625
7.1.2023 15:56:34 [Event] Prikol 37.215.49.53:61996 joins.
7.1.2023 15:56:34 [Notification] A client reconnected, resuming game calendar.
7.1.2023 15:57:01 [Notification] A Client attempts connecting via TCP, assigning client id 3
7.1.2023 15:57:01 [Notification] Client uid KukcZEa2XDMU/ypTgeLw0vBr attempting identification. Name: YourCreator
7.1.2023 15:57:01 [Notification] Sending server identification with remap False.  Server control privilege is True
7.1.2023 15:57:01 [Notification] Placing player at 73489,46875 110 48421,5
7.1.2023 15:57:02 [Event] Client disconnected.
7.1.2023 15:57:15 [Notification] A Client attempts connecting via TCP, assigning client id 4
7.1.2023 15:57:15 [Notification] Client uid KukcZEa2XDMU/ypTgeLw0vBr attempting identification. Name: YourCreator
7.1.2023 15:57:15 [Notification] Sending server identification with remap False.  Server control privilege is True
7.1.2023 15:57:15 [Notification] Placing player at 73489,46875 110 48421,5
7.1.2023 15:57:18 [Notification] A Client attempts connecting via TCP, assigning client id 5
7.1.2023 15:57:18 [Notification] Client uid MjlkNTA5OWY2OWNlZTY0Y2E2MjljMzlhMjI2OGJkMjI= attempting identification. Name: Dentes
7.1.2023 15:57:18 [Notification] Delayed join, need to load one spawn chunk first.
7.1.2023 15:57:18 [Notification] Sending server identification with remap False.  Server control privilege is False
7.1.2023 15:57:18 [Notification] Placing player at 58093,6999999881 115 41954,0532937624
7.1.2023 15:57:19 [Event] Client disconnected.
7.1.2023 15:57:27 [Event] YourCreator 127.0.0.1:58235 joins.
7.1.2023 15:57:30 [Notification] A Client attempts connecting via TCP, assigning client id 6
7.1.2023 15:57:30 [Notification] Client uid MjlkNTA5OWY2OWNlZTY0Y2E2MjljMzlhMjI2OGJkMjI= attempting identification. Name: Dentes
7.1.2023 15:57:30 [Notification] Delayed join, need to load one spawn chunk first.
7.1.2023 15:57:30 [Notification] Sending server identification with remap False.  Server control privilege is False
7.1.2023 15:57:30 [Notification] Placing player at 58093,6999999881 115 41954,0532937624
7.1.2023 15:57:43 [Event] Dentes 46.8.48.71:51460 joins.
7.1.2023 16:00:32 [Notification] Server ticking has been suspended
7.1.2023 16:00:32 [Notification] Autosaving game world. Notifying mods, then systems of save...
7.1.2023 16:00:32 [Notification] Defragmented listener lists
7.1.2023 16:00:32 [Event] Mods and systems notified, now saving everything...
7.1.2023 16:00:32 [Event] Will do offthread savegamedata saving...
7.1.2023 16:00:32 [Event] Saved player world data...
7.1.2023 16:00:32 [Event] Saved map regions...
7.1.2023 16:00:32 [Event] Saved map chunks...
7.1.2023 16:00:32 [Event] World saved! Saved 0 chunks, 0 mapchunks, 19 mapregions.
7.1.2023 16:00:32 [Notification] A client reconnected, resuming game calendar.
7.1.2023 16:00:32 [Notification] Server ticking has been resumed
7.1.2023 16:00:32 [Event] Saved 300 chunks...
7.1.2023 16:00:32 [Event] Offthread save of 415 chunks done.
7.1.2023 16:00:32 [Notification] Offthread save of 0 generating chunks done.
7.1.2023 16:00:33 [Event] Offthread save of 475 map chunks done.
7.1.2023 16:00:33 [Event] Offthread save of savegame done.
7.1.2023 16:05:34 [Notification] Server ticking has been suspended
7.1.2023 16:05:34 [Notification] Autosaving game world. Notifying mods, then systems of save...
7.1.2023 16:05:34 [Notification] Defragmented listener lists
7.1.2023 16:05:34 [Event] Mods and systems notified, now saving everything...
7.1.2023 16:05:34 [Event] Will do offthread savegamedata saving...
7.1.2023 16:05:34 [Event] Saved player world data...
7.1.2023 16:05:34 [Event] Saved map regions...
7.1.2023 16:05:34 [Event] Saved map chunks...
7.1.2023 16:05:34 [Event] World saved! Saved 0 chunks, 0 mapchunks, 13 mapregions.
7.1.2023 16:05:34 [Notification] A client reconnected, resuming game calendar.
7.1.2023 16:05:34 [Notification] Server ticking has been resumed
7.1.2023 16:05:34 [Event] Saved 300 chunks...
7.1.2023 16:05:34 [Event] Offthread save of 430 chunks done.
7.1.2023 16:05:34 [Notification] Offthread save of 0 generating chunks done.
7.1.2023 16:05:34 [Event] Offthread save of 497 map chunks done.
7.1.2023 16:05:34 [Event] Offthread save of savegame done.
7.1.2023 16:07:01 [Notification] Client Prikol tried to place a block but rejected because the client hand is empty
7.1.2023 16:10:35 [Notification] Server ticking has been suspended
7.1.2023 16:10:35 [Notification] Autosaving game world. Notifying mods, then systems of save...
7.1.2023 16:10:35 [Notification] Defragmented listener lists
7.1.2023 16:10:35 [Event] Mods and systems notified, now saving everything...
7.1.2023 16:10:35 [Event] Will do offthread savegamedata saving...
7.1.2023 16:10:35 [Event] Saved player world data...
7.1.2023 16:10:35 [Event] Saved map regions...
7.1.2023 16:10:35 [Event] Saved map chunks...
7.1.2023 16:10:35 [Event] World saved! Saved 0 chunks, 0 mapchunks, 21 mapregions.
7.1.2023 16:10:35 [Notification] A client reconnected, resuming game calendar.
7.1.2023 16:10:35 [Notification] Server ticking has been resumed
7.1.2023 16:10:35 [Event] Saved 300 chunks...
7.1.2023 16:10:35 [Event] Offthread save of 325 chunks done.
7.1.2023 16:10:35 [Notification] Offthread save of 0 generating chunks done.
7.1.2023 16:10:36 [Event] Offthread save of 523 map chunks done.
7.1.2023 16:10:36 [Event] Offthread save of savegame done.
7.1.2023 16:11:49 [Event] Игрок YourCreator вышел.
### Mods

```bash

```

### Screenshots

![image](https://user-images.githubusercontent.com/40342734/211152467-d0752915-ad47-461d-9af9-17d365a8c8e1.png)
![image](https://user-images.githubusercontent.com/40342734/211152478-f859e0b1-0eb1-4d8f-b101-706fc9849904.png)

**Comment by DArkHekRoMaNT** [comment]
Can not reproduce. Were there any other conditions? Are other players on the server also getting this bug?
